version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=db-user
      - DB_PASS=db-password
      - DB_NAME=db

  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      # - ./web/certbot:/etc/letsencrypt
    depends_on:
      - app

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:

networks:
  default:
    driver: bridge
