---
- name: Install and configure MySQL on the database server
  hosts: dbserver
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install MySQL
      apt:
        name:
          - mysql-server
          - python3-mysqldb
        state: present

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database and user
      mysql_user:
        name: db_user
        password: db_password
        priv: '*.*:ALL'
        state: present
